### ISSUE TITLE
Joomla exception "throw new DebugBarException("Session must be started before using stack data in the debug bar");"

### ISSUE THREAD

**Issue by morefriendm** [joomla-framework/application#106]
I have updated my website to Joomla 4.13 and using Postman to get data via Joomla 4 webservices. I have turned on the Debug. Now I'm getting a response to the Postman "Session must be started before using stack data in the debug bar" and it turns out /libraries/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php (line 447) throw new DebugBarException("Session must be started before using stack data in the debug bar"); is executing. Can you please help me? Thanks

**Comment by nibra** [comment]
Thank you for your report! However, it concerns the CMS and not the application package of the framework. Please report this error on github.com/joomla/joomla-cms.
