### ISSUE TITLE
WebClient.php. PHP 8.0. Undefined array key when user agent "Chrome Privacy Preserving Prefetch Proxy"

### ISSUE THREAD

**Issue by ReLater** [joomla-framework/application#112]
### Steps to reproduce the issue
- See https://github.com/joomla/joomla-cms/issues/39637

### Expected result
- User agent "Chrome Privacy Preserving Prefetch Proxy" is ignored by `elseif()`. https://github.com/joomla-framework/application/blob/2.0.2/src/Web/WebClient.php#L436
- No PHP warning.

### Actual result
- `Undefined array key 1 in libraries/vendor/joomla/application/src/Web/WebClient.php on line 439`

### Additional comments
- Maybe(?): https://github.com/joomla/joomla-cms/issues/39637#issuecomment-1383241989

**Comment by richard67** [comment]
It seems we have in general an issue when certain user agents are specified without a (numeric) version number. See also this CMS issue: https://github.com/joomla/joomla-cms/issues/44469 .

Unfortunately I think it is not fixed by the already merged PR #131 .

**Comment by richard67** [comment]
Please test #132 . Thanks in advance.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #132 . Thanks in advance.
