### ISSUE TITLE
WebClient.php deprecated elements on PHP8.1

### ISSUE THREAD

**Issue by joomdonation** [joomla-framework/application#114]
### Steps to reproduce the issue
Copied from https://github.com/joomla/joomla-cms/issues/39960

### Expected result
No warnings

### Actual result
Warnings when userAgent is null

**Comment by alikon** [comment]
please test #121

**Comment by alikon** [comment]
can be closed  now

**Comment by Hackwar** [comment]
With the fixes from @Quy this should now be solved and eventually show up in the next Joomla version.
