### ISSUE TITLE
Merge into one repository

### ISSUE THREAD

**Issue by rkgrep** [joomla-framework/application#55]
I propose to merge all repos into one, while subpackages can be automatically split as it is done with Laravel.
This will make contributing much more simple and allow to make dependent changes with one commit.

**Comment by mbabker** [comment]
I want to do this, but honestly I can't think of a way to put them all back together and keep the commit histories of each package without manually cherry-picking everything and that's not a time investment I have available to make at the moment personally (can't speak for anyone else on that topic).

**Comment by rkgrep** [comment]
What about making a new dev (3.0?) release without previous changes?
I know this will clear existing changes and contributors history. But this will give framework a fresh start.
Some packages are deprecated anyway, while some should be deprecated (e. g. Http package which can be replaced with guzzle).
Also API packages can still be maintained separately.

Old history will still be available in separate branches.

**Comment by rkgrep** [comment]
I've tried to merge packages, but something went wrong and some files are marked as rewritten instead of renamed, though all history is saved.
https://github.com/rkgrep/joomla-framework/tree/2.0-dev

**Comment by mbabker** [comment]
At this point it probably isn't happening, it'd be a lot of work to set up a new (poorly named) repos and packages and at this point the maintenance burden of 40 separate repos is more tolerable.
