### ISSUE TITLE
WebClient is out of date

### ISSUE THREAD

**Issue by photodude** [joomla-framework/application#59]
The WebClient portion is out of date.
It's missing new browsers like Edge, it's also missing the newer engines too (chrome changed engines to Blink, edge uses edgehtml). 

Reference
https://en.wikipedia.org/wiki/Comparison_of_web_browser_engines
#### Side note

We really should see if we can change all of the if/if-else cases to switch case or single `preg_match` cases.
I contributed a similar fix for Gantry 4's browser detection although the detection there is in a different and simpler format https://gist.github.com/photodude/a218a8018cb2e576336468c602441c79

**Comment by mbabker** [comment]
I honestly don't think this is a class we've got the manpower (or interested folks) to maintain, even though it (and its "unofficial" predecessor in the CMS, `JBrowser`) is something that has a lot of use cases and actual use in the code bases.  So there's a part of me that wants to turn this into a wrapper around another library if we can't get it updated and keep it maintained.

**Comment by photodude** [comment]
From my comment in the framework mailing list regarding the "The future of Joomla\Application\Client"

I was looking at this after helping to improve browser detection for a template framework. There is a lot that is not detected (edge for example), and somethings are attributed to the wrong rendering engine (chrome) because at some version the rendering engine in the browser changed. I had a hard time wrapping my head around the logic for how the WebClient browser detection worked or why it's setting the browser as a numeric constant. (basically I'm not sure how the consuming packages are using this library)

I think there is definitely interest in the WebClient browser detection being a separate package. 

There are also additional options for detection, currently we are using the [`$_SERVER['HTTP_USER_AGENT']`](http://php.net/manual/en/reserved.variables.server.php) constant, and then using custom parsing of the user_agent string. We could possibly [pull in the browscap.ini](http://browscap.org/) and use [`get_browser()`](http://php.net/manual/en/function.get-browser.php) to have a better object to work with. Although I'm not sure if pointing to a "custom" browscap.ini during runtime with ini_set('browscap', '[thebrowscap.ini file location]'); will give us the necessary ability to use [`get_browser()`](http://php.net/manual/en/function.get-browser.php) 

The alternative would be pulling in a fully built out browscap library https://github.com/browscap/browscap-php (a userland replacement for PHP's native get_browser() function)

**Comment by mbabker** [comment]
The actual values of the constants don't necessarily have to be something directly co-relating to what it represents.  So if you're doing something like `$client->platform === WebClient::IPOD` it doesn't matter if the `WebClient::IPOD` constant has a value of `6` (current value), `'ipod'`, or `'popular_handheld_device_sold_by_apple'`, as long as `WebClient::IPOD` then it's good enough.  That said, it's usually better to have the constant values co-relate in some form but it's not a major deal.

On the Framework side of things, I don't think it'd be a major issue requiring extra PHP configs to do something like `browscap`, but this does become a bit tricker considering the CMS consumes this class.

**Comment by wilsonge** [comment]
I've used this with very good results as well https://github.com/WhichBrowser/Parser

**Comment by photodude** [comment]
One thing I like about  https://github.com/ThaDafinser/UserAgentParser is it includes several options for providers, including https://github.com/WhichBrowser/Parser

**Comment by photodude** [comment]
Just realized there is an issue with both  https://github.com/ThaDafinser/UserAgentParser and https://github.com/WhichBrowser/Parser neither one supports PHP 5.3

looks like we might need to possibly pull in a `browscap.ini` and use `get_browser()` until we only support php 5.4 or 5.6

**Comment by photodude** [comment]
I've toyed with using https://github.com/ThaDafinser/UserAgentParser https://github.com/photodude/application/blob/patch-1/src/Web/WebClient.php
Unfortunately, it's only php 5.6+ and will need some additional work since the line between device and platform (i.e. OS) has been blurred in the detectPlatform method.

**Comment by photodude** [comment]
Appears to be partly addressed in #86 As such closing as fixed
