### ISSUE TITLE
[RFC] Deprecate CLI classes in favor of Console package

### ISSUE THREAD

**Issue by mbabker** [joomla-framework/application#75]
With the introduction of the Console package, is there any benefit in keeping the CLI class chain?  This package continues to serve as the base architecture for applications in general and holds the web focused application class chain, but IMO we do not need to provide two borderline competing implementations for the CLI architecture.

**Comment by roland-d** [comment]
We should remove the CLI classes if we are going to implement the Console package. There are already too many ways to do the same thing in Joomla. Let's try not to add more to that.

**Comment by rdeutz** [comment]
+1 on deprecate CLI classes

**Comment by wilsonge** [comment]
Kill it
