### ISSUE TITLE
What to do with get/set config methods

### ISSUE THREAD

**Issue by mbabker** [joomla-framework/application#84]
Bringing over relevant notes from joomla-framework/console#3 on the "issue" with our config interface's methods introduced in #83:

> There is a naming conflict between `Symfony\Component\Console\Application::get($name)` and `Joomla\Application\ConfigurationAwareApplicationInterface::get($name, $default)`. The Symfony method is used to get a `Symfony\Component\Console\Command\Command` object while the Joomla method is used to read a value from the configuration `Joomla\Registry\Registry`.

In effect, this leaves `Joomla\Console\Application` as a subclass of `Symfony\Component\Console\Application` and only implementing `Joomla\Application\ApplicationInterface` and unable to implement `Joomla\Application\ConfigurationAwareApplicationInterface`.  Quickest available options are reverting the Console changes, leaving us with 3K LOC to maintain simply because we can't subclass the Symfony application or introducing some painful B/C breaks in the Joomla ecosystem.

Before another 1.x tag can be made, this issue needs attention because we need to get this interface right before tagging a stable or we're stuck in B/C hell.

**Comment by wilsonge** [comment]
My opinion is sadly we should revert the console changes.

I'd have loved to ditch 3k lines of code but I don't think having spent years refactoring our shit from `getCfg` to `get` we should force refactoring back, especially when being practical fewer people are going to use the CLI than using `JFactory::getApplication->get()` in the CMS (and even on the framework level it's a frustrating to have to change our 'interface' (yes we didn't have a formal interface until 2.0-dev but effectively the AbstractApplication was that in framework 1.x) to add our new symfony feature in.

It definitely sucks though having the maintain the extra :(

**Comment by mbabker** [comment]
Part of the pain point is we're basically rewriting the entirety of the base Application and Command classes, and with that it almost makes using the upstream package pointless.  We can't integrate or consume anything that's written as a Symfony Console tool because our Application won't accept a Symfony Command and we're having to duplicate a lot of "internal" code because everything relies so heavily on those two base classes.

There's a part of me that almost feels like we're better off backing off on CLI support in Joomla, either the application or framework.  It's a third class citizen in the CMS ecosystem (not to mention fighting against the web oriented thinking of so much of the CMS API), and at the Framework level the choices are basically "force" symfony/console and break our ecosystem or build a half-assed Console package independent of Symfony since we already can't use it for its strongest attributes (about the only parts we actually can use are the input and output interfaces and Exception subclasses; the descriptors are hardcoded to the two main base classes and helpers are hit or miss plus there's a potential [deprecation of them](https://github.com/symfony/symfony/pull/27647)).

**Comment by wilsonge** [comment]
Yeah but we're never going to get a working CLI if everyone is creating their own Applications constantly. I think the concept of commands with a fixed CLI App is super important for cli in joomla, even if we don't necessarily go full blown in on everything after that.

**Comment by mbabker** [comment]
Fine, I will sit down to write my knockoff `symfony/console`.
